routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Modules\Website\Frontend\HomepageController@displayHomepage');

Auth::routes();

Route::get('/register-store', 'Modules\Marketplaces\Frontend\RegisterStoreController@create')->name('marketplaces.stores.register.create');
Route::post('/register-store', 'Modules\Marketplaces\Frontend\RegisterStoreController@store')->name('marketplaces.stores.register.store');

Route::get('/login-store', 'Modules\Marketplaces\Frontend\LoginStoreController@create')->name('marketplaces.stores.login.create');
Route::post('/login-store', 'Modules\Marketplaces\Frontend\LoginStoreController@store')->name('marketplaces.stores.login.store');

Route::get('/login-marketplace', 'Modules\Marketplaces\Frontend\LoginMarketplaceController@create')->name('marketplaces.login.create');
Route::post('/login-marketplace', 'Modules\Marketplaces\Frontend\LoginMarketplaceController@store')->name('marketplaces.login.store');

Route::get('/login-supervisor-group', 'Modules\Marketplaces\Frontend\LoginSupervisorGroupController@create')->name('marketplaces.supervisor-groups.login.create');
Route::post('/login-supervisor-group', 'Modules\Marketplaces\Frontend\LoginSupervisorGroupController@store')->name('marketplaces.supervisor-groups.login.store');

Route::get('/login-school', 'Modules\Marketplaces\Frontend\LoginSchoolController@create')->name('marketplaces.schools.login.create');
Route::get('/login-school/callback', 'Modules\Marketplaces\Frontend\LoginSchoolController@store')->name('marketplaces.schools.login.store');

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'example'], function() {
    Route::group(['prefix' => 'form'], function() {
        Route::get('/create', 'Examples\FormController@create');
        Route::post('/', 'Examples\FormController@store');
        Route::get('/{id}/edit', 'Examples\FormController@edit');
        Route::put('/{id}', 'Examples\FormController@update');
    });

    Route::group(['prefix' => 'flash'], function() {
        Route::get('/', 'Examples\FlashController@index');
    });

    Route::group(['prefix' => 'layout'], function() {
        Route::view('/', 'examples.blade.index');
    });

    Route::group(['prefix' => 'composer-views'], function() {
        Route::get('/', 'Examples\ComposerViewsController@index');
        Route::get('/{id}', 'Examples\ComposerViewsController@show');
        Route::get('/category/{category}', 'Examples\ComposerViewsController@filterByCategory');
    });

    Route::group(['prefix' => 'file-upload'], function() {
        Route::get('/basic', 'Examples\FileUploadController@create');
        Route::post('/basic', 'Examples\FileUploadController@store');
        Route::get('/multiple', 'Examples\MultipleFileUploadController@create');
        Route::post('/multiple', 'Examples\MultipleFileUploadController@store');
        Route::get('/image-resize', 'Examples\ImageResizeController@create');
        Route::post('/image-resize', 'Examples\ImageResizeController@store');
    });

    Route::resource('todos', 'Examples\ExampleTodosController', ['as'=>'examples']);
    Route::resource('send-email', 'Examples\SendEmailController', ['as'=>'examples']);
    Route::group(['prefix' => 'adminlte'], function() {
        Route::get('/', 'Examples\AdminlteController@index');
    });
    Route::resource('posts', 'Examples\ExamplePostsController', ['as'=>'examples']);
    Route::resource('trashed-posts', 'Examples\ExampleTrashedPostsController', ['as'=>'examples']);
    Route::resource('ajax-posts', 'Examples\ExampleAjaxPostsController', ['as'=>'examples']);

    Route::group(['prefix' => 'wilayah'], function() {
        Route::get('wilayah', 'Modules\Wilayah\Examples\WilayahIndonesiaController@index');
        Route::get('wilayah2', 'Modules\Wilayah\Examples\WilayahIndonesiaController@index2');
        Route::get('wilayah-k', 'Modules\Wilayah\Examples\WilayahIndonesiaController@indexKemdikbud');
        Route::get('wilayah-ro', 'Modules\Wilayah\Examples\WilayahIndonesiaController@indexRajaongkir');

        Route::get('kemdikbud', 'Modules\Wilayah\Examples\KemdikbudWilayahController@index');
        Route::get('kemdikbud2', 'Modules\Wilayah\Examples\KemdikbudWilayahController@index2');

        Route::get('rajaongkir', 'Modules\Wilayah\Examples\RajaongkirWilayahController@index');
        Route::get('rajaongkir2', 'Modules\Wilayah\Examples\RajaongkirWilayahController@index2');
    });

});

/**
 * /m                  : marketplaces.index
 * /m/{id}             : marketplaces.show
 * /m/{id}/c/{id}      : marketplaces.categories.show
 * /m/{id}/p           : marketplaces.products
 * /m/{id}/s           : marketplaces.stores.index
 *
 * /m/{id}/s/create        : marketplaces.stores.create
 * /m/{id}/s/{id}          : marketplaces.stores.show
 * /m/{id}/s/{id}/c/{id}   : marketplaces.stores.categories.show
 * /m/{id}/s/{id}/n        : marketplaces.stores.notes.index
 * /m/{id}/s/{id}/n/{id}   : marketplaces.stores.notes.show
 * /m/{id}/s/{id}/p-dis    : marketplaces.stores.product-discussions.index
 * /m/{id}/s/{id}/p-rev    : marketplaces.stores.product-reviews.index
 *
 * /m/{id}/s/{id}/p                : marketplaces.stores.products.index
 * /m/{id}/s/{id}/p/{id}           : marketplaces.stores.products.show
 * /m/{id}/s/{id}/p/{id}/dis       : marketplaces.stores.products.discussions.index
 * /m/{id}/s/{id}/p/{id}/dis/{id}  : marketplaces.stores.products.discussions.show
 * /m/{id}/s/{id}/p/{id}/rev       : marketplaces.stores.products.reviews.show
 *
 * cart                             : cart
 * checkout/{id}                    : checkout
 * checkout/{id}/billing-address    : checkout.payment-address
 * checkout/{id}/shipping-address   : checkout.shipping-address
 * checkout/{id}/shipping-method    : checkout.shipping-method
 * checkout/{id}/payment-method     : checkout.payment-method
 * checkout/{id}/confirm            : checkout.confirm
 *
 * su/p--{id} : shorturl.products.show
 * w/page/{id} : website.pages.show
 *
 * users/account/profile
 * users/account/password
 * users/account/addresses
 * users/account/orders
 *
 * dashboard/stores/{id}
 * dashboard/stores/{id}/profile
 * dashboard/stores/{id}/orders
 * dashboard/stores/{id}/collections
 * dashboard/stores/{id}/products
 * dashboard/stores/{id}/products/{id}/attributes
 * dashboard/stores/{id}/products/{id}/galleries
 * dashboard/stores/{id}/products/{id}/grouped-product-details
 * dashboard/stores/{id}/products/{id}/import-grouped-product-details
 * dashboard/stores/{id}/import-products
 * dashboard/stores/{id}/banners
 * dashboard/stores/{id}/banner-groups
 * dashboard/stores/{id}/product-collections
 * dashboard/stores/{id}/menus
 * dashboard/stores/{id}/notes
 * dashboard/stores/{id}/media-libraries
 * dashboard/stores/{id}/settings/addresses
 * dashboard/stores/{id}/settings/payment-methods
 * dashboard/stores/{id}/settings/shipping-methods
 * dashboard/stores/{id}/settings/store-settings
 * dashboard/stores/{id}/settings/addresses
 *
 * dashboard/marketplaces/{id}/profile
 * dashboard/marketplaces/{id}/categories
 * dashboard/marketplaces/{id}/stores
 * dashboard/marketplaces/{id}/banners
 * dashboard/marketplaces/{id}/banner-groups
 * dashboard/marketplaces/{id}/popular-searches
 * dashboard/marketplaces/{id}/store-collections
 * dashboard/marketplaces/{id}/products-collections
 * dashboard/marketplaces/{id}/media-libraries
 * dashboard/marketplaces/{id}/settings
 *
 * administrator
 * administrator/marketplaces
 * administrator/marketplace-collections
 * administrator/product-collections
 * administrator/banners
 * administrator/banner-groups
 * administrator/cms/layout-elements
 * administrator/cms/pages
 * administrator/cms/media-libraries
 * administrator/settings
 *
 */

/**
 * Marketplaces
 */
Route::group(['prefix' => 'm'], function() {
    Route::get('/', 'Modules\Marketplaces\Frontend\MarketplacesController@index')
        ->name('marketplaces.index');
    Route::get('create-marketplace', 'Modules\Marketplaces\Frontend\MarketplacesController@create')
        ->name('marketplaces.create')->middleware(['auth']);
    Route::post('create-marketplace', 'Modules\Marketplaces\Frontend\MarketplacesController@store')
        ->name('marketplaces.store')->middleware(['auth']);

    Route::get('delivery-status', 'Modules\Marketplaces\Frontend\DeliveryStatusController@index');
    Route::post('delivery-status-ajax', 'Modules\Marketplaces\Frontend\DeliveryStatusController@indexAjax');

    Route::get('all-stores', 'Modules\Marketplaces\Frontend\StoresController@displayAllStore');

    Route::get('{marketplace}', 'Modules\Marketplaces\Frontend\MarketplacesController@show')
        ->name('marketplaces.show');

    /**
     * Marketplace Store
     */
    Route::get('{marketplace}/s', 'Modules\Marketplaces\Frontend\StoresController@index')
        ->name('stores.index');
    Route::get('{marketplace}/create-store', 'Modules\Marketplaces\Frontend\StoresController@create')
        ->name('stores.create')->middleware(['auth']);
    Route::post('{marketplace}/create-store', 'Modules\Marketplaces\Frontend\StoresController@store')
        ->name('stores.store')->middleware(['auth']);

    /**
     * Marketplace Categories
     */
    Route::group(['prefix' => '{marketplace}/c'], function() {
        Route::get('{category}', 'Modules\Marketplaces\Frontend\MarketplaceCategoriesController@show')
            ->name('marketplaces.categories.show');
    });

    /**
     * Marketplace Products
     */
    Route::get('{marketplace}/p', 'Modules\Marketplaces\Frontend\MarketplaceProductsController@index')

app/Models/Modules/Marketplaces/Cart.php
<?php

namespace App\Models\Modules\Marketplaces;

use Illuminate\Database\Eloquent\Model;
use Cart as ShoppingCart;
use App\Models\Modules\Marketplaces\Store;

class Cart extends Model
{
    /*
    |--------------------------------------------------------------------------
    | GLOBAL VARIABLES
    |--------------------------------------------------------------------------
    */

    // protected $table = 'table';
    // protected $primaryKey = 'id';
    // public $timestamps = false;
    // protected $guarded = ['id'];
    protected $fillable = [
        'identifierable_type', 'identifierable_id',
        'instance', 'content',
    ];
    // protected $hidden = [];
    // protected $dates = [];

    /*
    |--------------------------------------------------------------------------
    | FUNCTIONS
    |--------------------------------------------------------------------------
    */
    public static function store($identifier, $instance)
    {
        $id = $identifier->id;
        $type = get_class($identifier);
        $content = ShoppingCart::instance($instance)->content();;

        static::updateOrCreate([
            'identifierable_type' => $type,
            'identifierable_id' => $id,
            'instance' => $instance,
        ], [
            'content' => serialize($content),
        ]);
    }

    public static function restore($identifier, $instance = null)
    {
        $id = $identifier->id;
        $type = get_class($identifier);

        $where = [
            'identifierable_type' => $type,
            'identifierable_id' => $id,
        ];

        if ($instance) {
            $where['instance'] = $instance;
        }

        $carts = static::where($where)->get();
        if (count($carts)) {
            foreach ($carts as $cart) {
                $instance = $cart->instance;

                $storeExists = Store::where('slug', $instance)->exists();
                if (!$storeExists) {
                    $cart->delete();
                    continue;
                }

                $contents = unserialize($cart->content);
                $isEmpty = ShoppingCart::instance($instance)->count() == 0;
                if ($isEmpty) {
                    foreach ($contents as $content) {
                        $item = ShoppingCart::instance($instance)->add($content->id, $content->name, $content->qty, $content->price);
                        $item->associate('App\Models\Modules\Marketplaces\Product');
                    }
                }
            }
        }
    }

    public static function remove($identifier, $instance = null)
    {
        $id = $identifier->id;
        $type = get_class($identifier);

        $where = [
            'identifierable_type' => $type,
            'identifierable_id' => $id,
        ];

        if ($instance) {
            $where['instance'] = $instance;
            static::where($where)->delete();
        }
    }

    /*
    |--------------------------------------------------------------------------
    | RELATIONS
    |--------------------------------------------------------------------------
    */
    public function identifierable()
    {
        return $this->morphTo();
    }

    /*
    |--------------------------------------------------------------------------
    | SCOPES
    |--------------------------------------------------------------------------
    */

    /*
    |--------------------------------------------------------------------------
    | ACCESORS
    |--------------------------------------------------------------------------
    */

    /*
    |--------------------------------------------------------------------------
    | MUTATORS
    |--------------------------------------------------------------------------
    */
}

app/Models/Modules/Marketplaces/GroupNotification.php
<?php

namespace App\Models\Modules\Marketplaces;

use Illuminate\Database\Eloquent\Model;
use App\Models\Modules\Marketplaces\Presenters\GroupNotificationTrait;

class GroupNotification extends Model
{
    use GroupNotificationTrait;

    /*
    |--------------------------------------------------------------------------
    | GLOBAL VARIABLES
    |--------------------------------------------------------------------------
    */

    // protected $table = 'table';
    // protected $primaryKey = 'id';
    // public $timestamps = false;
    // protected $guarded = ['id'];
    protected $fillable = [
        'groupable_type', 'groupable_id',
        'name', 'description', 'data',
        'read_at', 'read_by',
    ];
    // protected $hidden = [];
    // protected $dates = [];

    /*
    |--------------------------------------------------------------------------
    | FUNCTIONS
    |--------------------------------------------------------------------------
    */
    public static function addNotification($group, $name, $additionalData = [])
    {
        $groupableId = $group->id;
        $groupableType = get_class($group);

        static::create([
            'groupable_type' => $groupableType,
            'groupable_id' => $groupableId,
            'name' => $name,
            'description' => $additionalData['description'] ?? null,
            'data' => isset($additionalData['data']) ? json_encode($additionalData['data']) : null,
        ]);
    }

    public function setAsRead()
    {
        if (auth()->check()) {
            if (is_null($this->read_at)) {
                $userId = auth()->id();
                $this->read_at = date('Y-m-d H:i:s');
                $this->read_by = $userId;
                $this->save();

                return true;
            }
        }

        return false;
    }

    /*
    |--------------------------------------------------------------------------
    | RELATIONS
    |--------------------------------------------------------------------------
    */
    public function groupable()
    {
        return $this->morphTo();
    }

    public function user()
    {
        return $this->belongsTo('App\User', 'read_by');
    }

    /*
    |--------------------------------------------------------------------------
    | SCOPES
    |--------------------------------------------------------------------------
    */
    public function scopeUnread($query)
    {
        return $query->where('read_at', null);
    }

    /*
    |--------------------------------------------------------------------------
    | ACCESORS
    |--------------------------------------------------------------------------
    */
    public function getNotificationLabelAttribute()
    {
        return $this->fetchNotificationLabel();
    }

    public function getNotificationLinkAttribute()
    {
        return $this->fetchNotificationLink();
    }

    /*
    |--------------------------------------------------------------------------
    | MUTATORS
    |--------------------------------------------------------------------------
    */
}

resources/views/modules/marketplaces/backend/marketplaces/notifications/index.blade.php
@php
    /**
     * website settings
     */
    $favicon = null;
    $favicon = isset($websiteSettings['favicon']) && $websiteSettings['favicon'] ? $websiteSettings['favicon'] : false;
@endphp

@extends('themes.marika-natsuki.main')

@section('title', 'Notifications')

@push('meta')
    @if ($favicon)
        <link rel="icon" type="image/png" sizes="32x32" href="{{ asset($favicon) }}">
    @endif
@endpush

@push('css')
    <style>
        .mw-250 {
            max-width: 250px;
            display: inline-block;
        }
    </style>
@endpush

@push('js')
@endpush

@push('meta')
@endpush

@push('head_js')
@endpush

@section('content')

    @include('modules.marketplaces.frontend.inc.navbar-top-user')

    <div class="page-content">

        <div class="container">
            <div class="row">
                <div class="col-md-10 col-md-offset-1">

                    <ol class="breadcrumb">
                        <li>
                            <a href="{{ route('users.marketplaces.index', [$marketplace->id]) }}">Home</a>
                        </li>
                        <li class="active">
                            Notifications
                        </li>
                    </ol>

                    <h3>Notifications</h3>

                    @include('flash::message')

                    <div class="box mt-3">
                        <div class="box-content">
                            <div class="table-responsive">
                                <div class="mb-3">
                                    <a href="{{ route('users.marketplaces.notifications.index', [$marketplace->id, 'display' => 'all']) }}"
                                        class="btn {{ $display == 'all' ? 'btn-primary' : 'btn-default' }}">
                                        All
                                    </a>

                                    <a href="{{ route('users.marketplaces.notifications.index', [$marketplace->id, 'display' => 'unread']) }}"
                                        class="btn {{ $display == 'unread' ? 'btn-primary' : 'btn-default' }}">
                                        Unread
                                    </a>
                                </div>

                                <table class="table table-hover table-bordered">
                                    <thead>
                                        <tr>
                                            <th>No</th>
                                            <th>Options</th>
                                            <th>Deskripsi</th>
                                            <th>Waktu</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if (count($notifications))
                                            @php
                                                $no = $notifications->firstItem();
                                            @endphp
                                            @foreach ($notifications as $notification)
                                                <tr>
                                                    <td>{{ $no }}</td>
                                                    <td>
                                                        @if (is_null($notification->read_at))
                                                        {!! Form::open([
                                                            'route' => ['users.marketplaces.notifications.update', $marketplace->id, $notification->id],
                                                            'method' => 'PUT',
                                                            'style' => 'display: inline-block;'
                                                        ]) !!}
                                                            <button class="btn btn-xs btn-default" type="submit">
                                                                <i class="fa fa-fw fa-check text-success" title="Tandai sudah dibaca"></i>
                                                            </button>
                                                        {!! Form::close() !!}
                                                        @endif
                                                    </td>
                                                    <td>
                                                        @if (is_null($notification->read_at))
                                                            <i class="fa fa-fw fa-circle text-primary" title="Belum dibaca"></i>
                                                        @endif



                                                        @if ($notification->notification_link)
                                                            <a href="{{ $notification->notification_link }}"
                                                                title="{{ $notification->description }}">
                                                                {{ $notification->notification_label }}
                                                            </a>
                                                        @endif

                                                        @if (!$notification->notification_link)
                                                            <span title="{{ $notification->description }}">
                                                                {{ $notification->notification_label }}
                                                            </span>
                                                        @endif
                                                    </td>
                                                    <td>{{ $notification->created_at->diffForHumans() }}</td>
                                                </tr>
                                                @php
                                                    $no++;
                                                @endphp
                                            @endforeach
                                        @else
                                            <tr>
                                                <td colspan="9">No data</td>
                                            </tr>
                                        @endif
                                    </tbody>
                                </table>
                            </div>
                            {{ $notifications->links() }}
                        </div>
                    </div>



                </div>
            </div>
        </div>


    </div>

    @include('modules.marketplaces.backend.inc.sidebar-user-marketplace')
    @include('modules.marketplaces.frontend.inc.sidebar-cart')

    <button class="btn-back-to-top btn btn-skin" title="Go to top">
        <i class="fa fa-angle-up"></i>
    </button>

@endsection